# Generated by Django 3.0.7 on 2020-06-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'General'), (2, 'Guest'), (3, 'Accounting'), (4, 'IT')], default=1, max_length=30),
        ),
    ]
