# Generated by Django 3.0.7 on 2020-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200624_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'General'), (2, 'Guest'), (3, 'Accounting'), (4, 'IT')], default=1),
        ),
    ]
